### ISSUE TITLE
Build fails with error using VS2017.4

### ISSUE THREAD

**Issue by DavidXanatos** [startnine/filecommander#4]
I tried to build the project, but it fails with the below errors.
I am using a clean win10 VM with VS2017.4 installed.

Strangely on my win 7 host where I have multiple VS versions it compiled fine but did not run (it only showed the shadow of the window and no content)

`1>------ Erstellen gestartet: Projekt: RibbonFileManager.View, Konfiguration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3245: Dieser Verweis konnte nicht aufgelöst werden. Die "System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL"-Assembly wurde nicht gefunden. Stellen Sie sicher, dass die Assembly auf dem Datenträger vorhanden ist. Falls dieser Verweis im Code erforderlich ist, können Kompilierungsfehler auftreten.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2041,5): warning MSB3245: Dieser Verweis konnte nicht aufgelöst werden. Die "System.AddIn, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, processorArchitecture=MSIL"-Assembly wurde nicht gefunden. Stellen Sie sicher, dass die Assembly auf dem Datenträger vorhanden ist. Falls dieser Verweis im Code erforderlich ist, können Kompilierungsfehler auftreten.
1>C:\temp\RibbonFileManager-master\RibbonFileManager.View\Generated Files\IModule.g.cs(14,28,14,46): error CS0234: Der Typ- oder Namespacename "AddInBaseAttributeAttribute" ist im Namespace "System.AddIn.Pipeline" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.)
1>C:\temp\RibbonFileManager-master\RibbonFileManager.View\Generated Files\IModule.g.cs(14,28,14,46): error CS0234: Der Typ- oder Namespacename "AddInBaseAttribute" ist im Namespace "System.AddIn.Pipeline" nicht vorhanden. (Möglicherweise fehlt ein Assemblyverweis.)
2>------ Erstellen gestartet: Projekt: RibbonFileManager, Konfiguration: Debug Any CPU ------`

**Comment by logonoff** [comment]
Fixed, references should be now on GitHub.
