### ISSUE TITLE
Element order stacking issue

### ISSUE THREAD

**Issue by logonoff** [startnine/filecommander#5]
Running these versions:
- Windows 10 Professional build 17763.55 (October 2018 Update)
- https://github.com/StartNine/start9-ui/commit/c15c6ffa7ed001bdcad824338844a6ff7f6fc4c0
- https://github.com/StartNine/windows-sharp/commit/dcbcdb2876c6a84a7c70f17f9d5e18f6be0ddc13
-https://github.com/StartNine/ribbonfilemanager/commit/be9ff49a74895d38b2d4480d8b94fb2ad224ab16
- https://github.com/StartNine/NT6FileManagerBase/commit/34856a78a11431620bfa3c8e0677085c4edf4621,
when scrolling down the sidebar, the text and icons from the sidebar are above the menu bar, as seen here. The text should be behind the menu bar instead.  
 ![z-index issue](https://i.imgur.com/1Y82oJd.png0)

**Comment by reflectronic** [comment]
After asking Rob if this is fixed, I got this response back:
>I...think so?

So, closing this issue because it's either fixed or will be fixed after we do the skin juggling.
