### ISSUE TITLE
Unstyled window frame + titlebar on Win10

### ISSUE THREAD

**Issue by logonoff** [startnine/filecommander#6]
Running these versions:
- Windows 10 Professional build 17763.55 (October 2018 Update)
- https://github.com/StartNine/start9-ui/commit/c15c6ffa7ed001bdcad824338844a6ff7f6fc4c0
- https://github.com/StartNine/windows-sharp/commit/dcbcdb2876c6a84a7c70f17f9d5e18f6be0ddc13
-https://github.com/StartNine/ribbonfilemanager/commit/be9ff49a74895d38b2d4480d8b94fb2ad224ab16
- https://github.com/StartNine/NT6FileManagerBase/commit/34856a78a11431620bfa3c8e0677085c4edf4621,
the titebar and window frame for the window is unsyled, as seen below.
![unstyled window](https://i.imgur.com/gdpyeTE.png)

**Comment by ghost** [comment]
Shows on 8 aswell 
![image](https://user-images.githubusercontent.com/37509156/48676857-31ba8680-eb32-11e8-8db0-b6fdcb34a0b0.png)

**Comment by ghost** [comment]
other than everything works

**Comment by logonoff** [comment]
Fixed in https://github.com/StartNine/start9-ui/commit/0abdac1c4a5b5d73a473b84bc1f76070e5ee0e3e
