### ISSUE TITLE
Exception Unhandled in DiskItem.cs and WindowContent.xaml.cs during compilation

### ISSUE THREAD

**Issue by logonoff** [startnine/filecommander#7]
Running:
- Microsoft Windows [Version 10.0.17763.316] 
- .NET Core 3.0.0 Preview 3
- https://github.com/startnine/start9-ui/commit/d639cf41db028d8641c4d0528bb29645a1968bba
- ribbonfilemanager/https://github.com/startnine/ribbonfilemanager/commit/575e4efa1964e3e92462203f36158fc40e6a049f
- https://github.com/startnine/windows-sharp/commit/a7fc09a0075125af8768d0c26c6c8159b9ea3b76

During compilation, these errors are thrown:
line 47, ``DiskItem.cs``
![excerpt 1](https://i.imgur.com/gqc7bX7.png)  

line 151. ``WindowContent.xaml.cs``
![excerpt 2](https://i.imgur.com/FKpmMnz.png)

A very terrible solution is to comment out line 165 of ``MainWindow.xaml.cs``. However, that's what actually starts the initial tab when the program is starting.

Other solutions currently tried: 
- uncommenting line 212 in ``DiskItem.cs``
```cs
206        public DiskItem(String path)
207        {
208            ItemPath = Environment.ExpandEnvironmentVariables(path);
209            if (Directory.Exists(ItemPath))
210                ItemCategory = DiskItemCategory.Directory;
211
212            SetFSInfo(ItemPath); // this line
213
214            //WatchFileSystem();
215        }
```

**Comment by reflectronic** [comment]
On my end, it looks like the `DriveInfo.GetDrives()` API in .NET was returning a drive `D:\` even though I didn't have one, which tripped up `DiskItem`. I've fixed this issue on the end of this project, fix coming later.

**Comment by reflectronic** [comment]
Fixed in https://github.com/startnine/ribbonfilemanager/commit/c18c2ed85d8a299b0c88346fdf35f68c25fb0658 (I'd have to merge the branch to get it to auto-close so just gonna close it here)
